-- =============================================================
-- schema.sql
-- Offer Router Recovery — Complete Database Schema
-- Generated by code analysis (no original migration existed)
-- =============================================================
-- Confidence level is marked per table: HIGH / MEDIUM / LOW
-- HIGH  = every column, type, and constraint directly confirmed
--         by INSERT array keys or explicit column references in PHP
-- MEDIUM = column exists but type/size inferred from usage context
-- LOW   = column inferred indirectly; may need adjustment
-- =============================================================

CREATE DATABASE IF NOT EXISTS `efbhalvbhdsurl`
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE `efbhalvbhdsurl`;

-- =============================================================
-- TABLE: tbl_user
-- Confidence: HIGH
-- Evidence: library/User.php line 12 — fetch_data(DB_USER_TABLE,
--   ['user_name'=>..., 'password'=>...], 1)
--   DB_USER_TABLE = 'tbl_user' (Settings.php line 12)
-- =============================================================
CREATE TABLE IF NOT EXISTS `tbl_user` (
    `id`        INT          NOT NULL AUTO_INCREMENT,
    `user_name` VARCHAR(255) NOT NULL,
    `password`  VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_user_name` (`user_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================
-- TABLE: tbl_tag
-- Confidence: HIGH
-- Evidence: Offer.php lines 464-469 — INSERT array:
--   ['tag_name'=>..., 'created_at'=>date('Y-m-d')]
--   Filter.php line 22 — SELECT DISTINCT(network_name) shows
--   parallel structure for tbl_tag; fetch_data('tbl_tag',
--   ['tag_name'=>...]) and ['id'=>...] confirm id + tag_name
-- =============================================================
CREATE TABLE IF NOT EXISTS `tbl_tag` (
    `id`         INT          NOT NULL AUTO_INCREMENT,
    `tag_name`   VARCHAR(255) NOT NULL,
    `created_at` DATE         NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================
-- TABLE: tbl_network
-- Confidence: HIGH
-- Evidence: Offer.php lines 479-484 — INSERT array:
--   ['network_name'=>..., 'created_at'=>date('Y-m-d')]
--   Filter.php line 22 — SELECT DISTINCT(network_name) FROM tbl_network
--   Offer.php line 198 — fetch_data_new('tbl_network','id',
--     ['network_name'=>...], 1)
-- =============================================================
CREATE TABLE IF NOT EXISTS `tbl_network` (
    `id`           INT          NOT NULL AUTO_INCREMENT,
    `network_name` VARCHAR(255) NOT NULL,
    `created_at`   DATE         NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================
-- TABLE: tbl_offer_url
-- Confidence: HIGH
-- Evidence: Offer.php lines 588-596 — INSERT array (addNewOffer):
--   offer, slug_name, tag_id, note, network_id, start_date, end_date
--   Offer.php lines 29-34 — UPDATE array (archiveOffer/deleteOffer):
--   offer_status, status_updated_at
--   DB_OFFER_TABLE = 'tbl_offer_url' (Settings.php line 13)
--   offer_status values: 1=Active, 2=Archived, 3=Deleted (Offer.php lines 260-263)
--   status_updated_at NOT in INSERT → must be NULLable
--   start_date/end_date PHP fallback to date('Y-m-d') → NULLable safe
-- =============================================================
CREATE TABLE IF NOT EXISTS `tbl_offer_url` (
    `id`                INT          NOT NULL AUTO_INCREMENT,
    `offer`             VARCHAR(255) NOT NULL,
    `slug_name`         VARCHAR(255) NOT NULL,
    `tag_id`            INT              NULL,
    `note`              TEXT             NULL,
    `network_id`        INT              NULL,
    `offer_status`      TINYINT      NOT NULL DEFAULT 1,
    -- 1 = Active, 2 = Archived, 3 = Deleted
    `status_updated_at` DATE             NULL,
    `start_date`        DATE             NULL,
    `end_date`          DATE             NULL,
    PRIMARY KEY (`id`),
    -- Uniqueness enforced in PHP only for active offers (offer_status=1)
    -- DB-level index to support routing lookup by slug (every click hits this)
    KEY `idx_slug_name`   (`slug_name`),
    KEY `idx_offer_status`(`offer_status`),
    CONSTRAINT `fk_offer_tag`     FOREIGN KEY (`tag_id`)     REFERENCES `tbl_tag`    (`id`),
    CONSTRAINT `fk_offer_network` FOREIGN KEY (`network_id`) REFERENCES `tbl_network`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================
-- TABLE: tbl_sub_offer_url
-- Confidence: HIGH
-- Evidence: Offer.php lines 601-608 — INSERT array (new offer):
--   main_offer_id, sub_url, weight, status
--   (no deleted_status in new-offer INSERT → DEFAULT 'no' required)
--   Offer.php lines 534-543 — UPDATE array (edit offer, found with '-yes'):
--   main_offer_id, sub_url, weight, status, deleted_status='no'
--   Offer.php line 523 — UPDATE: deleted_status='yes', weight=0, status='no'
--   Postback.php line 13 — WHERE s.status = 'yes' AND s.deleted_status implicit
--   Offer.php line 83 — WHERE a.deleted_status="no"
--   weight used in float arithmetic with 0.0001 tolerance → DECIMAL(7,4)
-- =============================================================
CREATE TABLE IF NOT EXISTS `tbl_sub_offer_url` (
    `id`             INT            NOT NULL AUTO_INCREMENT,
    `main_offer_id`  INT            NOT NULL,
    `sub_url`        TEXT           NOT NULL,
    `weight`         DECIMAL(7,4)   NOT NULL DEFAULT 0,
    `status`         ENUM('yes','no') NOT NULL DEFAULT 'yes',
    `deleted_status` ENUM('yes','no') NOT NULL DEFAULT 'no',
    PRIMARY KEY (`id`),
    KEY `idx_main_offer_active` (`main_offer_id`, `status`, `deleted_status`),
    CONSTRAINT `fk_sub_offer_main` FOREIGN KEY (`main_offer_id`)
        REFERENCES `tbl_offer_url`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================
-- TABLE: tbl_click
-- Confidence: HIGH
-- Evidence: Postback.php lines 26-32 — INSERT array (rotateUrl):
--   click_id, offer_id, sub_offer_id, ip_address, created_at=>date('Y-m-d')
--   cron.php line 15 — GROUP BY created_at, offer_id confirms column names
--   ip_address VARCHAR(45) to support both IPv4 and IPv6
--   created_at is DATE not DATETIME (PHP date('Y-m-d') has no time component)
-- =============================================================
CREATE TABLE IF NOT EXISTS `tbl_click` (
    `id`           INT          NOT NULL AUTO_INCREMENT,
    `click_id`     VARCHAR(255)     NULL,
    `offer_id`     INT              NULL,
    `sub_offer_id` INT              NULL,
    `ip_address`   VARCHAR(45)      NULL,
    `created_at`   DATE         NOT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_click_offer_date` (`offer_id`, `created_at`),
    -- Note: no UNIQUE on click_id — PHP code does not prevent duplicate click_ids
    CONSTRAINT `fk_click_offer`     FOREIGN KEY (`offer_id`)
        REFERENCES `tbl_offer_url`(`id`),
    CONSTRAINT `fk_click_sub_offer` FOREIGN KEY (`sub_offer_id`)
        REFERENCES `tbl_sub_offer_url`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =============================================================
-- TABLE: tbl_report
-- Confidence: HIGH
-- Evidence: cron.php lines 30-32 — INSERT:
--   main_offer_id, main_offer_url, offer_clicks, report_date
--   cron.php line 21 — UPDATE: offer_clicks WHERE main_offer_id + report_date
--   cron.php line 19 — SELECT * FROM tbl_report WHERE report_date=? AND main_offer_id=?
--   Report.php line 13 — SELECT main_offer_id, main_offer_url,
--                          offer_clicks, report_date FROM tbl_report
--   UNIQUE on (main_offer_id, report_date): cron.php checks existence before
--   INSERT vs UPDATE — DB-level constraint makes this idempotent
-- =============================================================
CREATE TABLE IF NOT EXISTS `tbl_report` (
    `id`             INT          NOT NULL AUTO_INCREMENT,
    `main_offer_id`  INT              NULL,
    `main_offer_url` VARCHAR(255)     NULL,
    `offer_clicks`   INT          NOT NULL DEFAULT 0,
    `report_date`    DATE         NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_offer_report_date` (`main_offer_id`, `report_date`),
    KEY `idx_report_offer` (`main_offer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
